const ALGOKIT_DIR = '.algokit'
const SOURCES_DIR = 'sources'
const TEAL_FILE_EXT = '.teal'
const TEAL_SOURCEMAP_EXT = '.teal.tok.map'
const DEFAULT_MAX_SEARCH_DEPTH = 10

export { ALGOKIT_DIR, DEFAULT_MAX_SEARCH_DEPTH, SOURCES_DIR, TEAL_FILE_EXT, TEAL_SOURCEMAP_EXT }
