const ALGOKIT_DIR = '.algokit'
const SOURCES_DIR = 'sources'
const DEBUG_TRACES_DIR = 'debug_traces'
const TEAL_FILE_EXT = '.teal'
const TEAL_SOURCEMAP_EXT = '.teal.map'
const DEFAULT_MAX_SEARCH_DEPTH = 10

export { ALGOKIT_DIR, DEBUG_TRACES_DIR, DEFAULT_MAX_SEARCH_DEPTH, SOURCES_DIR, TEAL_FILE_EXT, TEAL_SOURCEMAP_EXT }
