name: Publish Docs to Dev Portal

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: docs/package.json
      - name: Install root dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish docs
        uses: algorandfoundation/devportal/.github/actions/publish-devportal-docs@ci/update-publish-devportal-docs-workflow
        with:
          docs-dir: docs
